[project]
name = "notes-editor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "boto3>=1.40.25",
    "pygit2>=1.13.3",
]
